name: Write apps manifest
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8.16' 
    - run: python build_apps_manifest.py
    - uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions